package com.study.emoticons.greendao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.study.emoticons.model.Configues;
import com.study.emoticons.model.Emoticons;
import com.study.emoticons.model.Image;

import com.study.emoticons.greendao.dao.ConfiguesDao;
import com.study.emoticons.greendao.dao.EmoticonsDao;
import com.study.emoticons.greendao.dao.ImageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig configuesDaoConfig;
    private final DaoConfig emoticonsDaoConfig;
    private final DaoConfig imageDaoConfig;

    private final ConfiguesDao configuesDao;
    private final EmoticonsDao emoticonsDao;
    private final ImageDao imageDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        configuesDaoConfig = daoConfigMap.get(ConfiguesDao.class).clone();
        configuesDaoConfig.initIdentityScope(type);

        emoticonsDaoConfig = daoConfigMap.get(EmoticonsDao.class).clone();
        emoticonsDaoConfig.initIdentityScope(type);

        imageDaoConfig = daoConfigMap.get(ImageDao.class).clone();
        imageDaoConfig.initIdentityScope(type);

        configuesDao = new ConfiguesDao(configuesDaoConfig, this);
        emoticonsDao = new EmoticonsDao(emoticonsDaoConfig, this);
        imageDao = new ImageDao(imageDaoConfig, this);

        registerDao(Configues.class, configuesDao);
        registerDao(Emoticons.class, emoticonsDao);
        registerDao(Image.class, imageDao);
    }
    
    public void clear() {
        configuesDaoConfig.clearIdentityScope();
        emoticonsDaoConfig.clearIdentityScope();
        imageDaoConfig.clearIdentityScope();
    }

    public ConfiguesDao getConfiguesDao() {
        return configuesDao;
    }

    public EmoticonsDao getEmoticonsDao() {
        return emoticonsDao;
    }

    public ImageDao getImageDao() {
        return imageDao;
    }

}
